---
version: "3"

includes:
  docker: docker/Taskfile.yaml

tasks:
  build:
    desc: "Build task-ui"
    deps:
      - fix
    cmds:
      - CGO_ENABLED=0 go build .

  test:
    desc: "Test task-ui"
    deps:
      - fix
    cmds:
      - CGO_ENABLED=1 go test -race -count=1 -cover ./...
      - CGO_ENABLED=0 go test -count=1 -cover ./...

  run:
    desc: "Run task-ui"
    deps:
      - build
    cmds:
      - ./task-ui --history-enable

  install:
    desc: "Install task-ui locally"
    deps:
      - fix
    cmds:
      - go install .

  fix:
    desc: "Fix code"
    deps:
      - deps:goimports
    cmds:
      - goimports -w .
      - go fmt ./...
      - go vet .
      - go mod tidy
      - ./README.md.sh > README.md

  deps:goimports:
    internal: true
    status:
      - type goimports
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
